// Generated by Haxe
(function (console) { "use strict";
var Demo = function() { };
Demo.main = function() {
	console.log("hello world");
};
Demo.main();
})(typeof console != "undefined" ? console : {log:function(){}});
